#! /bin/sh
DIR=`dirname $0`
DIR=`(cd $DIR ; pwd)`
INET_DIR=`(cd $DIR/../../inet4/src ; pwd)`
SIMULTE_DIR=`(cd $DIR/../../simulte/src ; pwd)`
VEINS_DIR=`(cd $DIR/../../veins/src/veins ; pwd)`
VEINS_INET_DIR=`(cd $DIR/../../veins/subprojects/veins_inet/src/veins_inet ; pwd)`
ARTERY_DIR=`(cd $DIR/../../artery/src; pwd)`
COMMAND_LINE_OPTIONS="-n $DIR/../simulations:$DIR:$INET_DIR:$SIMULTE_DIR:$ARTERY_DIR:$VEINS_DIR:$VEINS_INET_DIR"


if [ -f $DIR/libROVER.so -o -f $DIR/libROVER.dll -o -f $DIR/libROVER.dylib ]; then
  opp_run -l $DIR/ROVER $COMMAND_LINE_OPTIONS $*
elif [ -x $DIR/ROVER -o -x $DIR/ROVER.exe ]; then
  $DIR/lte $COMMAND_LINE_OPTIONS $*
elif [ -f $DIR/libROVER_dbg.so -o -f $DIR/libROVER_dbg.dll -o -f $DIR/libROVER_dbg.dylib ]; then
  exec opp_run -l $DIR/ROVER_dbg $COMMAND_LINE_OPTIONS $*
elif [ -x $DIR/ROVER_dbg -o -x $DIR/ROVER_dbg.exe ]; then
  $DIR/ROVER_dbg $COMMAND_LINE_OPTIONS $*
fi
