#! /bin/bash
DIR=`dirname $0`
DIR=`(cd $DIR ; pwd)`
INET_DIR=`(cd $DIR/../../inet4/src ; pwd)`
SIMU5G_DIR=`(cd $DIR/../../simu5g/src ; pwd)`
VEINS_DIR=`(cd $DIR/../../veins/src/veins ; pwd)`
VEINS_INET_DIR=`(cd $DIR/../../veins/subprojects/veins_inet/src/veins_inet ; pwd)`
ARTERY_DIR=`(cd $DIR/../../artery/src; pwd)`
COMMAND_LINE_OPTIONS="-n $DIR/../simulations:$DIR:$INET_DIR:$SIMU5G_DIR:$ARTERY_DIR:$VEINS_DIR:$VEINS_INET_DIR"

# use  executable first
if [ -x $DIR/CROWNET -o -x $DIR/CROWNET.exe ]; then
  echo "A"
  $DIR/CROWNET $COMMAND_LINE_OPTIONS $*
elif [ -x $DIR/CROWNET_dbg -o -x $DIR/CROWNET_dbg.exe ]; then
  echo "D"
  $DIR/CROWNET_dbg $COMMAND_LINE_OPTIONS $*
elif [ -f $DIR/libCROWNET.so -o -f $DIR/libCROWNET.dll -o -f $DIR/libCROWNET.dylib ]; then
  echo "B"
  opp_run -l $DIR/CROWNET $COMMAND_LINE_OPTIONS $*
elif [ -f $DIR/libCROWNET_dbg.so -o -f $DIR/libCROWNET_dbg.dll -o -f $DIR/libCROWNET_dbg.dylib ]; then
  echo "C"
  exec opp_run -l $DIR/CROWNET_dbg $COMMAND_LINE_OPTIONS $*
else
  echo "no executbale found!"
  exit -1
fi
