# ARC-DSA Experimental Validation Scenario - Default Parameter Values
#
# For detailed information on the applied algorithm refer to [1].
# 
# [1] S. Schuhbäck, L. Wischhof, J. Ott (2024): *Adaptive Transmission Rate Control for Decentralized Sensing Applications*, 
#     IEEE Access. [doi: 10.1109/ACCESS.2024.3495504](https://doi.org/10.1109/ACCESS.2024.3495504)

[Config Defaults]
abstract=true
description="configuration with a beacon and an entropy map application at each node"

output-scalar-file-append = false
print-undisposed = true
# experiment-label = ${datetime}
result-dir = results/${configname}/rep_${repetition}
output-scalar-file = ${resultdir}/${configname}.sca
output-vector-file = ${resultdir}/${configname}.vec
cmdenv-output-file = ${resultdir}/${configname}.out
seed-set = ${repetition}

# activate the next lines to store result files in SQLite format 
# outputvectormanager-class="omnetpp::envir::SqliteOutputVectorManager"
# outputscalarmanager-class="omnetpp::envir::SqliteOutputScalarManager"

# record relevant statistics
**.packetMeterIn.vector-recording = true
**.packetMeterOut.vector-recording = true
**.scalar-recording = true
**.statistic-recording = true
# note: to restrict file size of recorded vector data, set a more specific recording above and uncomment the following line
# **.vector-recording = false


# global parameters
**.coordConverterModule = "coordConverter"
**.identiyRegistryModule = "identiyRegistry"


*.flowController.typename = "" 

#============= ARC-DSA Packet Meter =================
# avg = (1-alpha)*avg + alpha*new_val (rtpc)
**.packetMeter.alpha = 0.0625


#============= All Apps =============================
*.ue[*].numApps = 2
*.ue[*].app[*].socket.typename = "UdpSocketManager"
# enable the next line to use the decentralized density map application as neighborhood size provider 
# (not required here since all nodes are in 1-hop range)
# *.ue[*].app[*].scheduler.neighborhoodSizeProvider = "^.^.app[1].app"
# use neighborhood table directly:
*.ue[*].app[*].scheduler.neighborhoodSizeProvider = "^.^.nTable"


#============= Beacon App ====================
*.ue[*].app[0].typename = "BeaconApp"
*.ue[*].app[0].app.typename = "BeaconDynamic"
# Note: Disable appending of resource sharing domain id since it is not applicable for WLAN
*.ue[*].app[0].app.appendResourceSharingDomainId = false  
# *.ue[*].app[0].app.startTime = uniform(0s,1000ms) # note: start time is set in ue_activity.ini

### Beacon scheduling ###
#generationInterval --> lower bound
*.ue[*].app[0].scheduler.generationInterval = 100ms
*.ue[*].app[0].scheduler.estimatedAvgPaketSize = 38B
*.ue[*].app[0].scheduler.maxApplicationBandwidth = 16kbps
*.ue[*].app[0].scheduler.numberPackets  = 1
*.ue[*].app[0].scheduler.startOffset = uniform(0ms, 100ms)

#============= Decentralized Map ====================
**.cellSize = 0.5m # artificially reduced cell size to generate more data in this small scenario
num-rngs = 2  # seperate random base for entropy map
## Entropy Map ##
*.ue[*].app[1].app.writeDensityLog = false
*.ue[*].app[1].typename = "DensityMapApp"
*.ue[*].app[1].socket.destPort = 30003
*.ue[*].app[1].socket.localPort = 30003
*.ue[*].app[1].app.typename = "EntropyMapAppSimple"
# *.ue[*].app[1].app.startTime = 0s # note: start time is set in ue_activity.ini

*.ue[*].app[1].app.mapCfg = crownet::MapCfg{ \
            writeDensityLog: true, \
            mapType: "ymf", \
            mapTypeLog: "all", \
            idStreamType: "insertionOrder"}
###  Entropy Map scheduling ### log: ymfPlusDistStep
# Schedule multiple packets in each interval
# generationInterval --> lower bound
# Note: While a typical generation interval would be in the range of seconds,
#       we artificially reduce the interval for this small laboratory scenario to
#       evaluate the effect of the ARC-DSA algorithm  
*.ue[*].app[1].scheduler.generationInterval = 100ms
*.ue[*].app[1].scheduler.startOffset = uniform(0ms, 1000ms)
*.ue[*].app[1].scheduler.estimatedAvgPaketSize = 70B # in paper [1] this was 1400B (assume full packet, reduced here due to small area)
*.ue[*].app[1].scheduler.maxApplicationBandwidth = 500kbps
#*.ue[*].app[1].scheduler.amountOfData  = 200MB # complet map
*.ue[*].app[1].scheduler.amountOfData  = -1B # based on fair share of application bandwidth 
*.ue[*].app[1].app.maxPduLength = 1400B


## Neighborhood Table ##
*.ue[*].nTable.typename = "crownet.neighbourhood.NeighborhoodTable"
*.ue[*].nTable.maxAge = 5s	# Time-to-Live (TTL) for NeighborhoodTable, i.e. how long node is considered active. 


## Neighborhood Client Table ##
*.ue[*].nTableClient.typename = "EntropyNeigborhoodTableClient"
*.ue[*].nTableClient.globalTable = "globalMeasurementMap"
*.ue[*].nTableClient.distance =  5.0 
#no max age for server/client based neighborhood table. There are no packets in this implementation
*.ue[*].app[1].app.neighborhoodTableModule = ".nTableClient"

#============= Mobility parameters ==================
**.mobility.constraintAreaMinZ = 0m
**.mobility.constraintAreaMaxZ = 0m

#============= Protocol stack parameters  ===========
**.configurator.config = xmldoc("./ip4Config.xml") # configuration of IPv4 addresses used in the network

#============= Positioning and mobility ============
*.gNB[0].mobility.initFromDisplayString = false


# set constrains for area according to size of
# shielded lab R1.009a
# **.coordConverter.xBound =  7.5m
# **.coordConverter.yBound = 10.0m

# config for OsgCoordConverterLocal
*.coordConverter.typename = "OsgCoordConverterLocal"
*.coordConverter.srs_code = "+proj=utm +zone=36 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
*.coordConverter.offset_x = -530473.4128825921m
*.coordConverter.offset_y = -5333543.991543822m
*.coordConverter.xBound = 7.5m
*.coordConverter.yBound = 10.0m

*.ue[*].middleware.typename = ""
*.ue[*].mobility.typename = "StationaryMobility"
*.ue[*].mobility.coordinateSystemModule = "coordConverter"
*.ue[*].mobility.initFromDisplayString = false

# Note: See coord_convert.py for information how these values are calculated:
*.gNB[0].mobility.initialLatitude = 48.15446231416398deg
*.gNB[0].mobility.initialLongitude = 33.40978745312782deg
*.ue[0].mobility.initialLatitude = 48.15443770501588deg
*.ue[0].mobility.initialLongitude = 33.40975028108362deg
*.ue[1].mobility.initialLatitude = 48.15443746534337deg
*.ue[1].mobility.initialLongitude = 33.40981750842778deg
*.ue[2].mobility.initialLatitude = 48.154445577140564deg
*.ue[2].mobility.initialLongitude = 33.409750343761274deg
*.ue[3].mobility.initialLatitude = 48.15444533746799deg
*.ue[3].mobility.initialLongitude = 33.40981757111572deg
*.ue[4].mobility.initialLatitude = 48.15445344926524deg
*.ue[4].mobility.initialLongitude = 33.40975040643897deg
*.ue[5].mobility.initialLatitude = 48.15445320959258deg
*.ue[5].mobility.initialLongitude = 33.40981763380369deg
*.ue[6].mobility.initialLatitude = 48.154461321389896deg
*.ue[6].mobility.initialLongitude = 33.40975046911669deg
*.ue[7].mobility.initialLatitude = 48.15446108171717deg
*.ue[7].mobility.initialLongitude = 33.40981769649169deg
*.ue[8].mobility.initialLatitude = 48.15446919351454deg
*.ue[8].mobility.initialLongitude = 33.40975053179443deg
*.ue[9].mobility.initialLatitude = 48.15446895384176deg
*.ue[9].mobility.initialLongitude = 33.40981775917972deg
*.ue[10].mobility.initialLatitude = 48.15447706563917deg
*.ue[10].mobility.initialLongitude = 33.4097505944722deg
*.ue[11].mobility.initialLatitude = 48.15447682596633deg
*.ue[11].mobility.initialLongitude = 33.40981782186777deg
*.ue[12].mobility.initialLatitude = 48.15448493776379deg
*.ue[12].mobility.initialLongitude = 33.40975065715deg
*.ue[13].mobility.initialLatitude = 48.154484698090876deg
*.ue[13].mobility.initialLongitude = 33.409817884555856deg

*.ue[*].mobility.speed = 0mps
#------------------------------------#

[Config Defaults-Density-Map]
abstract=true
extends=Defaults
description="configuration with an entropy map and an additional decentralized pedestrian density map"

*.ue[*].numApps = 3

## Density Map ##
*.ue[*].app[2].typename = "DensityMapApp"
*.ue[*].app[2].app.typename = "DensityMapAppSimple"
# *.ue[*].app[2].app.startTime = 0s # note: start time is set in ue_activity.ini
*.ue[*].app[2].app.mapCfg = crownet::MapCfgYmfPlusDistStep{ \
	writeDensityLog: true, \
	mapTypeLog: "ymfPlusDistStep", \
	cellAgeTTL: 40.0s, \
	alpha: 0.9, \
	stepDist: 60.0, \
	idStreamType: "insertionOrder", \
	appendRessourceSharingDomainId: false, \
	logType: "sql"}
### Density Map scheduling ###
# Schedule multiple packets in each interval
#generationInterval --> lower bound
*.ue[*].app[2].scheduler.generationInterval = 2s
*.ue[*].app[2].scheduler.startOffset = uniform(0s, 4000ms)
*.ue[*].app[2].scheduler.estimatedAvgPaketSize = 1400B # asume full packet
*.ue[*].app[2].scheduler.maxApplicationBandwidth = 150kbps
*.ue[*].app[2].scheduler.numberPackets  = -1
*.ue[*].app[2].scheduler.amountOfData  = -1B # based on fair share of application bandwidth 
*.ue[*].app[2].app.maxPduLength = 1400B


[Config ARC-DSA-Scheduler]
*.ue[*].app[*].scheduler.typename = "DynamicMaxBandwidthScheduler"
*.ue[*].app[1].scheduler.numberPackets  = -1  # should be determined dynamically

[Config Constant-Rate-Scheduler]
*.ue[*].app[*].scheduler.typename = "IntervalScheduler"
*.ue[*].app[1].scheduler.numberPackets  = 1   # is fixed to achieve a fixed rate
