# ARC-DSA Experimental Validation Scenario
#
# This scenario models a situation within the mobile communications laboratory R1.009a of Munich Universtiy of
# Applied Sciences.
#
# The scenario applies the ARC-DSA algorithm introduced in [1]. It estimates the local number of nodes sharing the bandwidth
# and uses an application layer scheduler to limit the total resources used for geospacial applications to a specific target
# rate. See [1] for more details.
#
# [1] S. Schuhbäck, L. Wischhof, J. Ott (2024): *Adaptive Transmission Rate Control for Decentralized Sensing Applications*, 
#     IEEE Access. [doi: 10.1109/ACCESS.2024.3495504](https://doi.org/10.1109/ACCESS.2024.3495504)
#
# Note: All important default values, e.g. the rate limits for the ARC-DSA algoritm for the applications (0: beacon 1:map)
#       *.ue[*].app[0].scheduler.maxApplicationBandwidth, are defined in ./defaults.ini

[General]
abstract = true

# Note: sim-time-limit is defined in ue_activity.ini

warmup-period=1s      # Note: When analyzing the results, you need to apply the same warmup-period to measurement data!
repeat = 4

network = crownet.simulations.networks.LabSingleCellCrowNet
image-path=../../images

# includes
include ./defaults.ini
include ./ue_activity.ini

# Artery specific general parameters
*.hasStoryboard = false
*.traci.typename = ""

# parameters of the density map
*.globalDensityMap.typename = "GlobalDensityMap"
*.globalDensityMap.vectorNodeModule = "misc" # pNode managed by BonnMotion
*.globalDensityMap.nodeModules = ""
*.globalDensityMap.traciModuleListener = ""		# no TraCI used
*.globalDensityMap.useSignalMapInit = false		# no TraCI used	
*.globalDensityMap.writeMapInterval = 1000ms
*.globalDensityMap.writerType = "sql"
*.globalDensityMap.mapSqlMaxCommitCount = 400

# parameters of the measurement map
*.globalMeasurementMap.typename = "GlobalEntropyMap"
*.globalMeasurementMap.vectorNodeModule = "misc"
*.globalMeasurementMap.nodeModules = ""
*.globalMeasurementMap.traciModuleListener = ""		# no TraCI used
*.globalMeasurementMap.useSignalMapInit = false		# no TraCI used	
*.globalMeasurementMap.writeMapInterval = 1000ms
*.globalMeasurementMap.writerType = "sql"
*.globalMeasurementMap.mapSqlMaxCommitCount = 400


*.globalMeasurementMap.entropyInterval = 0.1s
#*.globalMeasurementMap.entropyProvider = crownet::UniformEntropy{ 
#		minValue: 1.0, maxValue: 30.0, 
#		cellSelectionPropability: 0.70 }
*.globalMeasurementMap.entropyProvider = crownet::RndOffsetPolynomialEntropy{ coefficients : [0.0, 1.0,], cellSelectionPropability : 1.0, minValue: 10.0, maxValue: 30.0}

*.fileWriterRegister.typename = ""

[Config baseNR]
extends = Defaults
abstract = true
LabSingleCellCrowNet.hasCellular = true
LabSingleCellCrowNet.hasWlan= false
*.*ue[*].hasCellular = true
*.*ue[*].hasWlan = false
*.*ue[*].useNR = true
**.numBands = 50

#============= AMC module parameters ================
**.ueTxPower = 20dBm
**.eNodeBTxPower = 20dBm

*.*ue[*].cellularNic.typename = "NRNicUe"
*.*ue[*].cellularNic.mac.amcMode = "D2D" #"D2D"
*.*ue[*].cellularNic.address = "auto"

*.*NB[*].cellularNic.typename = "NRNicEnb"
*.*NB[*].cellularNic.mac.amcMode = "D2D"
*.*NB[*].mobility.coordinateSystemModule = "coordConverter"
**.rlc.um.mapAllLcidsToSingleBearer = true

# RLC parameters (as in OpenAirInterface Configuration)
**.rlc.um.queueSize = 5000000B              # OpenAirInterface queue limit for RLC_MODE_UM  (Commit f58ad3c39f04ca7305202749a7dad2b25ef6b942 file rlc.c  method rlc_data_req() line 478)
**.mac.queueSize = 10000B					# reduce MAC queue size - OpenAirInterface does not queue packets in mac layer
**.pdcpRrc.backgroundRlc = "UM"             # default RLC type (0: TM, 1: UM, 2: AM)



#============= Channel control parameters ===========
**.channelControl.pMax = 1W
**.channelControl.alpha = 1.0
**.channelControl.carrierFrequency = 2600e+6Hz

#============= Channel model parameters =============
# for a complete list of all parameters:
#   refer to LteChannelModels.ned
**.channelModel[0].shadowing = false   # enable/disable shadowing
**.channelModel[0].scenario = "INDOOR_HOTSPOT"  # pathloss scenario from ITU: INDOOR_HOTSPOT, URBAN_MICROCELL, URBAN_MACROCELL, RURAL_MACROCELL, SUBURBAN_MACROCELL
**.channelModel[0].nodeb_height = 1.5m
**.channelModel[0].ue_height = 1.5m
**.channelModel[0].building_height = 20m

**.channelModel[0].street_wide = 20m
**.channelModel[0].antennaGainUe = 0dBi
**.channelModel[0].antennGainEnB = 0dBi

**.channelModel[0].dynamic_los = false   # If true enable the possibility to switch dinamically the LOS/NLOS pathloss computation
**.channelModel[0].fixed_los = true      # If dynamic-los is false this parameter, if true, compute LOS pathloss otherwise compute NLOS pathloss
**.channelModel[0].fading = false        # Enable/disable fading
**.channelModel[0].fading_type = "JAKES" # Fading type (JAKES or RAYGHLEY) if fading is enabled
**.channelModel[0].fading_paths = 6      # If jakes fading this parameter specify the number of path (tap channel)
**.channelModel[0].delay_rms = 363e-9s

**.channelModel[0].extCell_interference = false # if true, enables the inter-cell interference computation for DL connections from external cells
**.channelModel[0].downlink_interference = true # if true, enables the inter-cell interference computation for DL connections
**.channelModel[0].uplink_interference = true   # if true, enables the interference computation for UL connections
**.channelModel[0].d2d_interference = true      # if true, enables the interference computation for D2D connections

*.*ue[*].macCellId = 1
*.*ue[*].servingNodeId = 1
*.*ue[*].nrServingNodeId = 1

*.*ue[*].radioDriver.dispatchInterfaceName = "cellular"

*.*ue[*].cellularNic.processingDelayIn = 5518us
*.*ue[*].cellularNic.processingDelayOut = 1134us
*.*ue[*].cellularNic.phy.d2dEnforceEnbBoundOnSideLink = true

*.*ue[*].ipv4.configurator.interfaces = "cellular"
*.*ue[*].ipv4.configurator.addressBase = "20.0.0.0"
*.*ue[*].ipv4.configurator.netmask = "255.0.0.0"

*.configurator.config = xmldoc("ip4Config_cellular.xml")
*.ue[*].app[*].scheduler.checkNetworkConnectivity = true

### Select CQI for D2D transmissions ###
# One-to-Many communications work with fixed CQI values only. Set the parameter **.usePreconfiguredTxParams and
# select the desired CQI using the parameter **.d2dCqi
**.usePreconfiguredTxParams = true
**.d2dCqi = 7

[Config baseWLAN]
extends = Defaults
abstract = true
LabSingleCellCrowNet.hasCellular = false
LabSingleCellCrowNet.hasWlan= true
*.*ue[*].hasCellular = false
*.*ue[*].hasWlan = true
*.*ue[*].numWlanNic = 1

*.*ue[*].radioDriver.dispatchInterfaceName = "wlanNic0"

*.*ue[*].ipv4.configurator.interfaces = "wlanNic0"
*.*ue[*].ipv4.configurator.addressBase = "20.0.0.0"
*.*ue[*].ipv4.configurator.netmask = "255.0.0.0"
*.*ue[*].ipv4.forwarding = true
*.*ue[*].ipv4.multicastForwarding = true
*.*ue[*].ipv4.ip.limitedBroadcast = true
*.*ue[*].ipv4.ip.directBroadcastInterfaces = "wlanNic0"
*.*ue[*].ipv4.igmp.enabled = false

*.configurator.config = xmldoc("ip4Config_wlan.xml")

# configure all UE apps to use WLAN broadcast for socket communication
*.*ue[*].app[*].socket.destAddresses ="255.255.255.255"
*.*ue[*].app[*].socket.multicastInterface = "wlanNic0"
*.*ue[*].app[*].socket.joinLocalMulticastGroups = false

# configure WLAN model to use ad-hoc mode (direct communication, no access point)
*.*ue[*].wlanNic[*].mgmt.typename = "Ieee80211MgmtAdhoc"
*.*ue[*].wlanNic[*].agent.typename = ""
*.*ue[*].wlanNic[*].radio.antenna.mobilityModule = "^.^.^.mobility"


# for WLAN in ad-hoc mode, connectivity information is not available
*.ue[*].app[*].scheduler.checkNetworkConnectivity = false

[Config single-ue-NR]
extends = baseNR, ARC-DSA-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=1}

[Config single-ue-WLAN]
extends = baseWLAN, ARC-DSA-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=1}

[Config two-ue-NR]
extends = baseNR, ARC-DSA-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=2}

[Config two-ue-WLAN]
extends = baseWLAN, ARC-DSA-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=2}

[Config four-ue-NR]
extends = baseNR, ARC-DSA-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=4}

[Config four-ue-WLAN]
extends = baseWLAN, ARC-DSA-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=4}

[Config upto-14-ue-NR]
extends = baseNR, ARC-DSA-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=14}

[Config upto-14-ue-WLAN]
extends = baseWLAN, ARC-DSA-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=14}

[Config upto-14-ue-ramp-NR]
extends = baseNR, ARC-DSA-Scheduler, UEs-Activity-Ramp-Up-Down
*.numUe = ${numUEs=14}

[Config upto-14-ue-ramp-WLAN]
extends = baseWLAN, ARC-DSA-Scheduler, UEs-Activity-Ramp-Up-Down
*.numUe = ${numUEs=14}

[Config upto-14-ue-burst-NR]
extends = baseNR, ARC-DSA-Scheduler, UEs-Activity-Bursts
*.numUe = ${numUEs=14}

[Config upto-14-ue-burst-WLAN]
extends = baseWLAN, ARC-DSA-Scheduler, UEs-Activity-Bursts
*.numUe = ${numUEs=14}


# fixed rate scenarios (only for comparison/as baseline scenarios)

[Config noarc-upto-14-ue-NR]
extends = baseNR, Constant-Rate-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=14}

[Config noarc-upto-14-ue-WLAN]
extends = baseWLAN, Constant-Rate-Scheduler, UEs-Activity-Always
*.numUe = ${numUEs=14}

[Config noarc-upto-14-ue-ramp-NR]
extends = baseNR, Constant-Rate-Scheduler, UEs-Activity-Ramp-Up-Down
*.numUe = ${numUEs=14}

[Config noarc-upto-14-ue-ramp-WLAN]
extends = baseWLAN, Constant-Rate-Scheduler, UEs-Activity-Ramp-Up-Down
*.numUe = ${numUEs=14}

[Config noarc-upto-14-ue-burst-NR]
extends = baseNR, Constant-Rate-Scheduler, UEs-Activity-Bursts
*.numUe = ${numUEs=14}

[Config noarc-upto-14-ue-burst-WLAN]
extends = baseWLAN, Constant-Rate-Scheduler, UEs-Activity-Bursts
*.numUe = ${numUEs=14}





