#include "SqlLiteSchema.h"

namespace crownet {

    const char SQL_CREATE_TABLES[] =
        "PRAGMA foreign_keys = OFF; \n"
        "PRAGMA synchronous = OFF; \n"
        "PRAGMA journal_mode = MEMORY; \n"
        "PRAGMA cache_size = -2000; \n"
        "PRAGMA page_size = 8192; \n"
        "BEGIN IMMEDIATE TRANSACTION; \n"
        "CREATE TABLE IF NOT EXISTS 'dcd_map' \n"
        "( \n"
            "uid             INTEGER PRIMARY KEY, \n"
            "hostId          INTEGER NOT NULL, \n"
            "simtime         REAL NOT NULL, \n"
            "x               REAL NOT NULL, \n"
            "y               REAL NOT NULL, \n"
            "count           REAL, \n"
            "measured_t      REAL, \n"
            "received_t      REAL, \n"
            "source          REAL, \n"
            "selection       INTEGER, \n"
            "selectionRank   REAL, \n"
            "sourceHost      REAL, \n"
            "sourceEntry     REAL, \n"
            "hostEntry       REAL, \n"
            "rsd_id          INTEGER, \n"
            "own_cell        INTEGER, \n"
            "owner_rsd_id    INTEGER, \n"
            "FOREIGN KEY ('selection') REFERENCES 'alg_mapping' ('uid') \n"
        ");\n"
        "CREATE INDEX IF NOT EXISTS 'dcd_map_idx_hostId' ON 'dcd_map' (hostId); \n"
        "CREATE TABLE IF NOT EXISTS 'alg_mapping' \n"
        "( \n"
            "uid             INTEGER PRIMARY KEY, \n"
            "alg_name        TEXT \n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS 'dcd_map_glb' \n"
        "( \n"
            "uid             INTEGER PRIMARY KEY, \n"
            "simtime         REAL NOT NULL, \n"
            "x               REAL NOT NULL, \n"
            "y               REAL NOT NULL, \n"
            "count           REAL \n"
        ");\n"
        "CREATE TABLE IF NOT EXISTS 'glb_node_id_mapping' \n"
        "(\n"
            "uid             INTEGER PRIMARY KEY, \n"
            "glb_map_uid     INTEGER NOT NULL, \n"
            "node_id         INTEGER NOT NULL, \n"
            "FOREIGN KEY ('glb_map_uid') REFERENCES 'dcd_map_glb' ('uid')"
        ");\n"
        "CREATE INDEX IF NOT EXISTS 'dcd_map_glb_idx_simtime' ON 'dcd_map_glb' (simtime); \n"
        "\n"
        "CREATE TABLE IF NOT EXISTS 'metadata' \n"
        "( \n"
            "uid             INTEGER PRIMARY KEY, \n"
            "hostId          INTEGER NOT NULL, \n"
            "key             TEXT NOT NULL, \n"
            "value           TEXT, \n"
            "UNIQUE(hostId, key)\n"
        ");\n"
        "\n"
        "COMMIT TRANSACTION; \n"
        "\n"
;
}
