//
// Generated file, do not edit! Created by nedtool 5.6 from rover/applications/common/AppCommon.msg.
//

#ifndef __APPCOMMON_M_H
#define __APPCOMMON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef ROVER_API
#  if defined(ROVER_EXPORT)
#    define ROVER_API  OPP_DLLEXPORT
#  elif defined(ROVER_IMPORT)
#    define ROVER_API  OPP_DLLIMPORT
#  else
#    define ROVER_API
#  endif
#endif



class CurrentLocationTag;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/applications/base/ApplicationPacket_m.h" // import inet.applications.base.ApplicationPacket

#include "inet/common/geometry/Geometry_m.h" // import inet.common.geometry.Geometry

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

/**
 * Class generated from <tt>rover/applications/common/AppCommon.msg:23</tt> by nedtool.
 * <pre>
 * class CurrentLocationTag extends inet::TagBase
 * {
 *     inet::Coord location;
 * }
 * </pre>
 */
class ROVER_API CurrentLocationTag : public ::inet::TagBase
{
  protected:
    inet::Coord location;

  private:
    void copy(const CurrentLocationTag& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CurrentLocationTag&);

  public:
    CurrentLocationTag();
    CurrentLocationTag(const CurrentLocationTag& other);
    virtual ~CurrentLocationTag();
    CurrentLocationTag& operator=(const CurrentLocationTag& other);
    virtual CurrentLocationTag *dup() const override {return new CurrentLocationTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const inet::Coord& getLocation() const;
    virtual inet::Coord& getLocationForUpdate() { return const_cast<inet::Coord&>(const_cast<CurrentLocationTag*>(this)->getLocation());}
    virtual void setLocation(const inet::Coord& location);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CurrentLocationTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CurrentLocationTag& obj) {obj.parsimUnpack(b);}

#endif // ifndef __APPCOMMON_M_H

