#!/bin/bash

echo ""
echo "### CrowNet Enviroment Setup ###"

echo "CROWNET_HOME: ${CROWNET_HOME}"
echo "CROWNET_IMAGE_REG: ${CROWNET_IMAGE_REG}"
echo "CROWNET_IMAGE_BASE: ${CROWNET_IMAGE_BASE}"
echo "CROWNET_IMAGE_DEFAULT_TAG: ${CROWNET_IMAGE_DEFAULT_TAG}"
echo ""
