#!/bin/bash

check_container() {
        REQUIRED_CONTAINER=$1
        LOCAL_CONTAINERS=$(docker image list --format "{{.Repository}}:{{.Tag}}")
        
        echo "the local containers are: ${LOCAL_CONTAINERS[*]}"
         
        REQUIRED_CONTAINER2=${REQUIRED_CONTAINER#$CROWNET_IMAGE_BASE/}
        LOCAL_CONTAINERS2=$(docker image list --format "{{.Repository}}:{{.Tag}}" | grep -o '[^/]*$')
        
	if [[ "${LOCAL_CONTAINERS[*]}" =~ "${REQUIRED_CONTAINER}" ]]; then
	    echo >&2 "  Available:   ${REQUIRED_CONTAINER}"
	else
		if [[ "${LOCAL_CONTAINERS2[*]}" =~ "${REQUIRED_CONTAINER2}" ]]; then
		      echo >&2 "(!) Warning: image found for ${REQUIRED_CONTAINER2} but under different registry."
                    RENAME=$((RENAME+1))
		else   
		    echo >&2 "(!) Missing:   ${REQUIRED_CONTAINER}"
	            MISSING=$((MISSING+1)) 
		fi
	fi
}

check_containers_local_available() {

	MISSING=0
        RENAME=0

	echo >&2  ""
	echo >&2  "Check availability of images."
	echo >&2  ""
	echo >&2  "------------------------- IMAGE AVAILABILITY ------------------------------"
	echo >&2  "Local           Container name   "                                             
	echo >&2  "---------------------------------------------------------------------------"
	check_container "${CROWNET_IMAGE_BASE}/omnetpp:${CROWNET_OPP_CONT_TAG}"
	check_container "${CROWNET_IMAGE_BASE}/vadere:${CROWNET_VADERE_CONT_TAG}"
	check_container "${CROWNET_IMAGE_BASE}/flowcontrol:${CROWNET_CONTROL_CONT_TAG}"
	check_container "${CROWNET_IMAGE_BASE}/sumo:${CROWNET_SUMO_CONT_TAG}"
	check_container "${CROWNET_IMAGE_BASE}/omnetpp-ide:${CROWNET_OPP_IDE_CONT_TAG}"
	check_container "${CROWNET_IMAGE_BASE}/vadere-ide:${CROWNET_VADERE_IDE_CONT_TAG}"
	check_container "${CROWNET_IMAGE_BASE}/flowcontrol-ide:${CROWNET_CONTROL_IDE_CONT_TAG}"

	echo >&2 "---------------------------------------------------------------------------"
        echo >&2 " "
   
        MISS=$(($MISSING+$RENAME))
	if [ "$MISS" -gt 0 ]; then
           printf >&2 'Not all images are available on your local machine. Missing: %d out of 7.\n' $MISS
        else
           echo >&2 "All required images available on your local machine. No build or pull is necessary." 
        fi

        echo $MISS

}

##################################### MAIN SCRIPT ######################################

echo "The following images are required for the simulation: "
sh ${CROWNET_HOME}/scripts/print_container_versions
sh ${CROWNET_HOME}/scripts/print_container_registry

missing=$(check_containers_local_available)



if ! [ "$missing" = "0" ]; then
   echo -n "Pull the specified images from a container registry? (y/N): "
   read answer
   if [ "$answer" != "${answer#[Yy]}" ] ;then
   
        echo "From which container registry would you like to pull ?"
   	echo "(1) https://github.com/roVer-HM/crownet (open access)" 
   	echo "(2) https://sam-dev.cs.hm.edu/rover/crownet (restricted access): "
	echo "(3) other container registry (access permissions unknown)"
	read -p 'Option: ' OPTION
	echo $OPTION

	case "$OPTION" in
	   "1") 
		SOURCE_IMAGE_BASE="ghcr.io/rover-hm" 
	   ;;
	   "2") 
		SOURCE_IMAGE_REG="sam-dev.cs.hm.edu:5023" 
		SOURCE_IMAGE_BASE="sam-dev.cs.hm.edu:5023/rover/crownet"
		docker login $SOURCE_IMAGE_REG 
	   ;;
	   "3") 
                echo ""
		echo "Please provide the URL to the container registry to which your repo references. For example for github, use 'ghcr.io/namespace/repo'" 
		read -p 'registry URL:' SOURCE_IMAGE_BASE
		echo "Please provide the URL to the registry provider. For example for github, use 'ghcr.io'" 
		read -p 'host URL:' SOURCE_IMAGE_REG
                echo ""
               docker login $SOURCE_IMAGE_REG
                
	   ;;
	esac
   
   
         bash $CROWNET_HOME/scripts/pull_and_push_images -s $SOURCE_IMAGE_BASE -t $CROWNET_IMAGE_BASE
         if [ $? -eq 0 ]; then
		echo "All images have been downloaded successfully."
                exit 0	  
	 else
	        echo "Image download failed. Make sure that the images are available under ${SOURCE_IMAGE_BASE}."	
                fi
	 fi 
fi



















