#!/bin/bash
# Start script for the omnetpp-inet container.
# In addition to the omnetpp simulation environment, this container includes the
# projects inet, simulte and veins.
#
# By default, the latest version will be started. In order to start a different version
# add the version number as first argument. For example: "omnetpp 5.3" will start
# a containter with the 5.3 release. For a list of available containers, refer to the
# docker registry or the wiki of the project.
#
# Furthermore, the script can be called with the parameter "exec" and a specific
# command to be executed within the container.
#
# Examples:
#
# "omnetpp"		will start the OMNeT++ IDE in the latest OMNeT++ container
# "omnetpp 5.3"		will start the OMNeT++ IDE in the OMNeT++ 5.3 container
# "omnetpp exec ls"	will start the command "ls" in the latest OMNeT++ container
# "omnetpp 5.3 exec ls"	will start the command "ls" in the OMNeT++ 5.3 container

SHORTNAME=omnetpp-inet
COMMAND=omnetpp

if [ -z "${CROWNET_OPP_CONT_TAG}" ]; then
      echo "Variabel 'CROWNET_OPP_CONT_TAG' not set. Did you source $CROWNET_HOME/scrips/crownetenv?"
      exit -1
fi

if [[ -z "$1" || "$1" == "exec" ]]; then
      VERSION=$CROWNET_OPP_CONT_TAG
      CONTNAME=$SHORTNAME-$VERSION
else
      VERSION=omnetpp-$1
      SHORTNAME=$SHORTNAME-$1
      CONTNAME=$SHORTNAME
fi

if [[ "$1" == "exec" ]]; then
      COMMAND="$2 $3 $4 $5 $6 $7 $8 $9"
fi

if [[ "$2" == "exec" ]]; then
      COMMAND="$3 $4 $5 $6 $7 $8 $9"
fi

if [ -z "$CROWNET_IMAGE_BASE" ]; then
      echo "Variabel 'CROWNET_IMAGE_BASE' not set. Did you source $CROWNET_HOME/scrips/crownetenv?"
      exit -1
fi

IMAGENAME=$CROWNET_IMAGE_BASE/$CONTNAME

source "$( cd "$(dirname "$0")" ; pwd -P )"/lib/lib.sh

run_individual_container $SHORTNAME $CONTNAME $IMAGENAME $COMMAND

