#!/bin/bash
# Start script for the omnetpp container.
#
# By default, the latest version will be started. In order to start a different version
# add the version number as first argument. For example: "omnetpp 5.3" will start
# a containter with the 5.3 release. For a list of available containers, refer to the
# docker registry or the wiki of the project.
#
# Furthermore, the script can be called with the parameter "exec" and a specific
# command to be executed within the container.
#
# Examples:
#
# "omnetpp-ide"	 will start the OMNeT++ IDE in the latest OMNeT++ container
# "omnetpp exec ls"	 will start the command "ls" in the latest OMNeT++ container
# "omnetpp 5.3 exec ls" will start the command "ls" in the OMNeT++ 5.3 container

SHORTNAME=omnetpp
COMMAND=omnetpp
CONTNAME=omnetpp

if [[ -z "$1" || "$1" == "exec" || "$1" == "execs" ]]; then
      VERSION=latest
      CONTNAME=$SHORTNAME:$VERSION
else
      VERSION=omnetpp-$1
      SHORTNAME=$SHORTNAME-$1
      CONTNAME=$CONTNAME:$1
fi

# if the script was started with an "exec" argument,
# forward all parameters following the "exec"
if [[ "$1" == "exec" ]]; then
      COMMAND="${@:2:${#@}+1-2}"
fi

if [[ "$2" == "exec" ]]; then
      COMMAND="${@:3:${#@}+1-3}"
fi

if [[ "$1" == "execs" ]]; then
      COMMAND="${@:2:${#@}+1-2}"
      SILENT=y
fi

if [[ "$2" == "execs" ]]; then
      COMMAND="${@:3:${#@}+1-3}"
      SILENT=y
fi

IMAGENAME=sam-dev.cs.hm.edu:5023/rover/crownet/$CONTNAME

source "$( cd "$(dirname "$0")" ; pwd -P )"/lib/lib.sh

# Variant 2: Start an individual container for each run
run_individual_container $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
