#!/bin/bash

SHORTNAME=omnetpp
COMMAND=omnetpp
CONTNAME=omnetpp-ide

if [ -z "${CROWNET_OPP_CONT_TAG}" ]; then
      echo "Variable 'CROWNET_OPP_CONT_TAG' not set. Did you source $CROWNET_HOME/setup?"
      exit -1
fi

if [[ -z "$1" || "$1" == "exec" ]]; then
      VERSION=$CROWNET_OPP_CONT_TAG
      CONTNAME=$CONTNAME:$VERSION
else
      VERSION=omnetpp-$1
      SHORTNAME=$SHORTNAME-$1
      CONTNAME=$CONTNAME:$1
fi

# if the script was started with an "exec" argument,
# forward all parameters following the "exec"
if [[ "$1" == "exec" ]]; then
      COMMAND="${@:2:${#@}+1-2}"
fi

if [[ "$2" == "exec" ]]; then
      COMMAND="${@:3:${#@}+1-3}"
fi

if [ -z "$CROWNET_IMAGE_BASE" ]; then
      echo "Variabel 'CROWNET_IMAGE_BASE' not set. Did you source $CROWNET_HOME/scrips/crownetenv?"
      exit -1
fi

IMAGENAME=$CROWNET_IMAGE_BASE/$CONTNAME

source "$( cd "$(dirname "$0")" ; pwd -P )"/lib/lib.sh

# Start an individual container for each run
# echo $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
run_individual_container $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
