#!/bin/sh
docker run --rm -it -v "$(pwd):/root/models" -u "$(id -u):$(id -g)" omnetpp/omnetpp:u18.04-5.5.1
# docker run --rm -it -v "$(pwd):/root/models" -u "$(id -u):$(id -g)" omnetpp/inet:o5.5.1-4.1.1
