#!/bin/bash

if [[ -z $ROVER_MAIN ]];then
  echo "Variable ROVER_MAIN not set."
  exit -1
fi


if [[ ! "${#@}" -eq 2 ]];then
  echo "need omnetpp.ini and config"
  exit -1
fi

OPP_INI="$1"
CONFIG="$2"
source $ROVER_MAIN/scripts/nedpath > /dev/null

CMD_ARR=(exec opp_run)
CMD_ARR+=(-u Cmdenv)
CMD_ARR+=(-c "$CONFIG")
# CMD_ARR+=("--cmdenv-redirect-output=true")
CMD_ARR+=("--cmdenv-stop-batch-on-error=true")
CMD_ARR+=(-l "$ROVER_MAIN/inet4/src/INET")
CMD_ARR+=(-l "$ROVER_MAIN/rover/src/ROVER")
CMD_ARR+=(-l "$ROVER_MAIN/simulte/src/lte")
CMD_ARR+=(-l "$ROVER_MAIN/veins/src/veins")
CMD_ARR+=(-l "$ROVER_MAIN/veins/subprojects/veins_inet/src/veins_inet")
CMD_ARR+=("$OPP_INI")
echo "workingdir: $PWD"
echo "$ROVER_MAIN/scripts/omnetpp ${CMD_ARR[@]}"
echo ""
$ROVER_MAIN/scripts/omnetpp "${CMD_ARR[@]}"
