#!/bin/bash

echo ""
echo "-----------------------------ENVIRONMENT-----------------------------------"
echo "CROWNET_HOME=${CROWNET_HOME}"
echo "PATH=${PATH}"
echo "OPP_EXTERNAL_DATA_MNT=${OPP_EXTERNAL_DATA_MNT:-None} (addional docker mount point)"
echo "---------------------------------------------------------------------------"
echo ""












