#!/bin/bash

echo ""
echo "-----------------------------ENVIRONMENT-----------------------------------"
echo "CROWNET_HOME=${CROWNET_HOME}"
echo "PATH=${PATH}"
echo "---------------------------------------------------------------------------"
echo ""












