#!/bin/bash

if [[ -z $CROWNET_HOME ]];then
  echo "Variable CROWNET_HOME not set."
  exit -1
fi


if [[ ! "${#@}" -ge 2 ]];then
  echo "need omnetpp.ini and config"
  exit -1
fi

if [[ -z $3 ]];then
    EXPERIMENT="experiment-$(date +"%Y-%m-%d-%s")"
else
    EXPERIMENT=$3
fi

OPP_INI="$1"
CONFIG="$2"

echo "$EXPERIMENT"

source $CROWNET_HOME/scripts/nedpath > /dev/null

CMD_ARR=(exec opp_run)
CMD_ARR+=(-u Cmdenv)
CMD_ARR+=(-c "$CONFIG")
CMD_ARR+=("--experiment-label=$EXPERIMENT")
CMD_ARR+=("--cmdenv-stop-batch-on-error=true")
CMD_ARR+=(-l "$CROWNET_HOME/inet4/src/INET")
CMD_ARR+=(-l "$CROWNET_HOME/rover/src/ROVER")
CMD_ARR+=(-l "$CROWNET_HOME/simulte/src/lte")
CMD_ARR+=(-l "$CROWNET_HOME/veins/src/veins")
CMD_ARR+=(-l "$CROWNET_HOME/veins/subprojects/veins_inet/src/veins_inet")
CMD_ARR+=("$OPP_INI")
echo "workingdir: $PWD"
echo "running command:"
echo "$CROWNET_HOME/scripts/omnetpp ${CMD_ARR[@]}"
echo ""
$CROWNET_HOME/scripts/omnetpp "${CMD_ARR[@]}"
