#!/bin/bash

SHORTNAME=sumo
CONTNAME=$SHORTNAME

if [ -z "${CROWNET_SUMO_CONT_TAG}" ]; then
      echo "Variabel 'CROWNET_SUMO_CONT_TAG' not set. Did you source $CROWNET_HOME/scrips/crownetenv?"
      exit -1
fi

if [[ -z "$1" || "$1" == "exec" ]]; then
    TAG_DIGEST=":${CROWNET_SUMO_CONT_TAG}"
    CONTNAME=$SHORTNAME
else
    TAG_DIGEST=$1
    SHORTNAME=$SHORTNAME
    CONTNAME=$SHORTNAME
fi

if [ -z "$CROWNET_IMAGE_BASE" ]; then
      echo "Variabel 'CROWNET_IMAGE_BASE' not set. Did you source $CROWNET_HOME/scrips/crownetenv?"
      exit -1
fi

IMAGENAME=$CROWNET_IMAGE_BASE/$SHORTNAME$TAG_DIGEST

source "$( cd "$(dirname "$0")" ; pwd -P )"/lib/lib.sh

# run new individual container execute (and wrap) command after exec
# argument.
if [[ "$1" == "exec" ]]; then
      COMMAND="${@:2:${#@}+1-2}"
      run_individual_container $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
      exit $?
fi

if [[ "$2" == "exec" ]]; then
      COMMAND="${@:3:${#@}+1-3}"
      run_individual_container $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
      exit $?
fi

run_individual_container $SHORTNAME $CONTNAME $IMAGENAME /init.sh $@
