#!/bin/bash

SHORTNAME=vadere
COMMAND=idea.sh
CONTNAME=vadere-ide

if [ -z "${CROWNET_IMAGE_DEFAULT_TAG}" ]; then
      echo "Variabel 'CROWNET_IMAGE_DEFAULT_TAG' not set. Did you source $CROWNET_HOME/scrips/crownetenv?"
      exit -1
fi

if [[ -z "$1" || "$1" == "exec" ]]; then
      VERSION=$CROWNET_IMAGE_DEFAULT_TAG
      CONTNAME=$CONTNAME:$VERSION
else
      SHORTNAME=$SHORTNAME-$1
      CONTNAME=$CONTNAME:$1
fi

if [[ "$1" == "exec" ]]; then
      COMMAND="${@:2:${#@}+1-2}"
      # COMMAND="$2 $3 $4 $5 $6 $7 $8 $9"
fi

if [[ "$2" == "exec" ]]; then
      COMMAND="${@:3:${#@}+1-3}"
      # COMMAND="$3 $4 $5 $6 $7 $8 $9"
fi

if [ -z "$CROWNET_IMAGE_BASE" ]; then
      echo "Variabel 'CROWNET_IMAGE_BASE' not set. Did you source $CROWNET_HOME/scrips/crownetenv?"
      exit -1
fi

IMAGENAME=$CROWNET_IMAGE_BASE/$CONTNAME

echo "container> used image: $IMAGENAME"

source "$( cd "$(dirname "$0")" ; pwd -P )"/lib/lib.sh

# Variant 2: Start an individual container for each run
#echo $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
run_individual_container $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
