#!/usr/bin/python3
"""
Search for all scenario files in ROVER_MAIN and list them in a tkinter
Listbox. Open selected project via 'Enter' inside the vadere container.
"""
import glob
import os
import subprocess
import sys


if __name__ == "__main__":

    cmd = [
        f"{os.environ['ROVER_MAIN']}/scripts/vadere",
        "exec",
        "java",
        "-jar",
        "/opt/vadere/vadere/VadereGui/target/vadere-gui.jar",
    ]
    p = subprocess.Popen(
        cmd,
        cwd=os.path.curdir,
        stdin=None,
        env=os.environ.copy(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    while p.poll() is None:
        sout = p.stdout.readline()
        print(sout.decode("utf-8"), end="")

    print(p.stdout.read().decode("utf-8"), end="")
    for err in p.stderr.readlines():
        print(err.decode("utf-8"), end="")
    p.kill()
