#!/bin/bash

if [[ -z $CROWNET_HOME ]];then
    echo "CROWNET_HOME not set"
    exit -1
fi

if [[ -z "$1" ]]; then
    $CROWNET_HOME/scripts/vadere exec java -jar /opt/vadere/vadere/VadereGui/target/vadere-postvis.jar
else
    $CROWNET_HOME/scripts/vadere $1 exec java -jar /opt/vadere/vadere/VadereGui/target/vadere-postvis.jar
fi

