#!/bin/bash

SHORTNAME=vadere
CONTNAME=$SHORTNAME

# if [[ -z "$1" || "$1" == "exec" ]]; then
#       VERSION=latest
#       CONTNAME=$SHORTNAME-$VERSION
# else
#       VERSION=omnetpp-$1
#       SHORTNAME=$SHORTNAME-$1
#       CONTNAME=$SHORTNAME
# fi
#
IMAGENAME=sam-dev.cs.hm.edu:5023/rover/rover-main/$SHORTNAME
#
source "$( cd "$(dirname "$0")" ; pwd -P )"/lib/lib.sh
#
# # run new individual container execute (and wrap) command after exec
# # argument.
# if [[ "$1" == "exec" ]]; then
#       COMMAND="${@:2:${#@}+1-2}"
#       run_individual_container $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
#       exit $?
# fi
#
# if [[ "$2" == "exec" ]]; then
#       COMMAND="${@:3:${#@}+1-3}"
#       run_individual_container $SHORTNAME $CONTNAME $IMAGENAME $COMMAND
#       exit $?
# fi

run_start_container $SHORTNAME $CONTNAME $IMAGENAME /init.sh $@
