#!/bin/sh
cd `dirname $0`
../../src/run_rover -n .:../src $*
# for shared lib, use: opp_run -l ../../src/ROVER -n .:../src $*

# in order to execute a single configuration (in the case "S1") in GUI mode use:
# omnetpp exec ./run -c S1

# in order to execute a single configuration (in the case "S1") in command-line mode use:
# omnetpp exec ./run -u Cmdenv -c S1

# in order to perform all runs of a configuration, use opp_runall to start this script, e.g.:
# omnetpp exec opp_runall ./run -c S1
