#!/bin/bash
#
# run all configurations/scenarios of this simulation

confs=( S1 S1-UA S1-25 S1-25-UA S2 S2-UA S2-25 S2-25-UA S3 S3-UA)

for i in "${confs[@]}"
do
   : 
   echo "Running $i"
   opp_runall ./run -c $i &
done

echo "All configs are started -- waiting for completion..."
wait
echo "Done."
