#! /bin/bash
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

if [[ "$1" == "release" || "$1" == "debug" ]]; then
    _MODE="$1"
    shift
else 
    _MODE="release"
fi

if [[ "$_MODE" == "release" ]]; then
    _Dbg=""
else
    _Dbg="_dbg"
fi

# echo "MODE: $_MODE /  $_Dbg" 
MAKE="make MODE=${_MODE}"

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
export NEDPATH="$(exec ../../../scripts/nedpath)"

echo "opp_test run $OPT work${_Dgb} -v $TESTFILES -a -c final"
opp_test run $OPT -p "work${_Dbg}" -v $TESTFILES -a "-c final" || exit 1
echo
echo Results can be found in ./work