#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE="make MODE=release"

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
export NEDPATH=.

CROWNET_PATH="../../../src/"
CROWNET_INCLUDE="-I$CROWNET_PATH -L$CROWNET_PATH"

INET_PATH="../../../../inet4/src/"
INET_INCLUDE="-I$INET_PATH -L$INET_PATH"

EXTRA_INCLUDES="$CROWNET_INCLUDE $INET_INCLUDE -lINET -lCROWNET"

opp_test gen $OPT -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f --deep --no-deep-includes -o work -i ../makefrag $EXTRA_INCLUDES; $MAKE) || exit 1
echo
opp_test run $OPT -p work -v $TESTFILES || exit 1
echo
echo Results can be found in ./work